title: Alvin Haryanto # your name (or website title) here
logo: "/images/logo.png?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist 
  San Francisco Bay Area 
  <br><br>
  <a href="https://www.linkedin.com/in/alvinharyanto/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-163959090-1 # your Google Analytics tracking ID here
